import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ChevronLeft, Code2, Copy, CheckCircle2 } from 'lucide-react';

const LANGUAGES = ['TypeScript', 'Python', 'Rust', 'Go', 'Java', 'C++'];

const SAMPLE_OUTPUT = `// Generated by BeeHive Coding Agent
function fibonacci(n: number): number {
  if (n <= 1) return n;
  return fibonacci(n - 1) + fibonacci(n - 2);
}

console.log(fibonacci(10)); // 55`;

export default function CodingPage() {
  const [prompt, setPrompt] = useState('');
  const [language, setLanguage] = useState('TypeScript');
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const generate = () => {
    if (!prompt.trim()) return;
    setOutput(SAMPLE_OUTPUT);
  };

  const copyCode = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="center-col">
      <header className="topbar">
        <h1 className="topbar-title">Coding</h1>
      </header>
      <div className="content-scroll">
        <Link to="/negocios" style={{ fontSize: 12.5, color: 'var(--text-muted)', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 4, marginBottom: 16 }}>
          <ChevronLeft size={14} /> Back to Negócios
        </Link>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="chat-panel" style={{ marginBottom: 0 }}>
            <div className="chat-panel-header">
              <h2 className="chat-title">Code Generator</h2>
              <div className="chat-selectors">
                {LANGUAGES.map((lang) => (
                  <button
                    key={lang}
                    onClick={() => setLanguage(lang)}
                    className="selector-pill"
                    style={{
                      borderColor: language === lang ? 'var(--primary)' : 'var(--border)',
                      color: language === lang ? 'var(--primary-light)' : 'var(--text-secondary)',
                    }}
                  >
                    {lang}
                  </button>
                ))}
              </div>
            </div>
            <div className="chat-input-box" style={{ marginBottom: 0 }}>
              <input
                type="text"
                placeholder="Descreva o código que deseja gerar..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && generate()}
              />
              <div className="chat-input-actions">
                <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{language}</span>
                <button className="input-send-btn" onClick={generate}>
                  <Code2 size={16} />
                </button>
              </div>
            </div>
          </div>

          {output && (
            <div className="chat-panel" style={{ marginBottom: 0 }}>
              <div className="chat-panel-header">
                <h2 className="chat-title">Output</h2>
                <button className="icon-square-btn" onClick={copyCode}>
                  {copied ? <CheckCircle2 size={15} style={{ color: 'var(--success)' }} /> : <Copy size={15} />}
                </button>
              </div>
              <pre
                style={{
                  background: 'var(--surface-2)',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--radius-sm)',
                  padding: 16,
                  fontSize: 12.5,
                  fontFamily: 'monospace',
                  color: 'var(--text-secondary)',
                  overflowX: 'auto',
                  lineHeight: 1.6,
                  whiteSpace: 'pre',
                }}
              >
                {output}
              </pre>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
